name: SoapUI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y default-jre wget tar

    - name: Run SoapUI tests
      run: ./run-soapui.sh

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: soapui-test-report
        path: reports/
